import type { Publisher, ReleaseNotes, OutputFormat } from '@cullit/core';
import { formatNotes, fetchWithTimeout, escapeHtml, createLogger } from '@cullit/core';

const log = createLogger();

interface ConfluenceSearchResponse {
  results?: Array<{ id: string; version: { number: number } }>;
}

interface ConfluencePagePayload {
  type: 'page';
  title: string;
  space: { key: string };
  body: {
    storage: { value: string; representation: 'storage' };
  };
  ancestors?: Array<{ id: string }>;
}

/**
 * Publishes release notes as a Confluence page.
 * Requires CONFLUENCE_EMAIL, CONFLUENCE_API_TOKEN, and a publish target with:
 *   - domain: yourcompany.atlassian.net
 *   - spaceKey: the Confluence space key
 *   - parentPageId (optional): parent page to nest under
 */
export class ConfluencePublisher implements Publisher {
  private domain: string;
  private email: string;
  private apiToken: string;
  private spaceKey: string;
  private parentPageId?: string;

  constructor(config: { domain: string; spaceKey: string; parentPageId?: string }) {
    if (!config.domain || !/^[a-zA-Z0-9.-]+\.atlassian\.net$/.test(config.domain)) {
      throw new Error('Invalid Confluence domain — expected format: yourcompany.atlassian.net');
    }
    if (!config.spaceKey || !/^[A-Z][A-Z0-9_]{0,30}$/.test(config.spaceKey)) {
      throw new Error('Invalid Confluence spaceKey — expected uppercase letters, digits, or underscores');
    }

    this.domain = config.domain;
    this.spaceKey = config.spaceKey;
    this.parentPageId = config.parentPageId;

    this.email = process.env.CONFLUENCE_EMAIL || process.env.JIRA_EMAIL || '';
    this.apiToken = process.env.CONFLUENCE_API_TOKEN || process.env.JIRA_API_TOKEN || '';

    if (!this.email || !this.apiToken) {
      throw new Error('Confluence credentials not configured. Set CONFLUENCE_EMAIL and CONFLUENCE_API_TOKEN (or JIRA_EMAIL and JIRA_API_TOKEN).');
    }
  }

  async publish(notes: ReleaseNotes, format: OutputFormat, preformatted?: string): Promise<void> {
    const htmlBody = format === 'html'
      ? (preformatted || formatNotes(notes, 'html'))
      : this.notesToConfluenceHtml(notes);

    const title = `Release ${notes.version} — ${notes.date}`;

    const existing = await this.findPage(title);
    if (existing) {
      await this.updatePage(existing.id, existing.version + 1, title, htmlBody);
      log.info(`✓ Updated Confluence page: ${title}`);
    } else {
      await this.createPage(title, htmlBody);
      log.info(`✓ Created Confluence page: ${title}`);
    }
  }

  private notesToConfluenceHtml(notes: ReleaseNotes): string {
    const categoryLabels: Record<string, string> = {
      features: '✨ Features', fixes: '🐛 Bug Fixes', breaking: '⚠️ Breaking Changes',
      improvements: '🔧 Improvements', chores: '🧹 Chores', other: '📝 Other',
    };
    const order = ['breaking', 'features', 'improvements', 'fixes', 'chores', 'other'];

    let html = '';
    if (notes.summary) {
      html += `<p>${escapeHtml(notes.summary)}</p>`;
    }

    const grouped = new Map<string, typeof notes.changes>();
    for (const change of notes.changes) {
      const list = grouped.get(change.category) || [];
      list.push(change);
      grouped.set(change.category, list);
    }

    for (const cat of order) {
      const entries = grouped.get(cat);
      if (!entries?.length) continue;
      html += `<h3>${categoryLabels[cat] || cat}</h3><ul>`;
      for (const e of entries) {
        html += `<li>${escapeHtml(e.description)}`;
        if (e.ticketKey) html += ` <code>${escapeHtml(e.ticketKey)}</code>`;
        html += `</li>`;
      }
      html += `</ul>`;
    }

    if (notes.metadata) {
      html += `<p><em>Generated by Cullit • ${notes.metadata.commitCount} commits, ${notes.metadata.prCount} PRs</em></p>`;
    }

    return html;
  }

  private async findPage(title: string): Promise<{ id: string; version: number } | null> {
    const url = new URL(`https://${this.domain}/wiki/rest/api/content`);
    url.searchParams.set('title', title);
    url.searchParams.set('spaceKey', this.spaceKey);
    url.searchParams.set('expand', 'version');

    const res = await fetchWithTimeout(url.toString(), { headers: this.headers() });
    if (!res.ok) return null;

    const data = await res.json() as ConfluenceSearchResponse;
    const page = data.results?.[0];
    if (!page) return null;
    return { id: page.id, version: page.version.number };
  }

  private async createPage(title: string, body: string): Promise<void> {
    const payload: ConfluencePagePayload = {
      type: 'page',
      title,
      space: { key: this.spaceKey },
      body: {
        storage: { value: body, representation: 'storage' },
      },
    };

    if (this.parentPageId) {
      payload.ancestors = [{ id: this.parentPageId }];
    }

    const res = await fetchWithTimeout(`https://${this.domain}/wiki/rest/api/content`, {
      method: 'POST',
      headers: this.headers(),
      body: JSON.stringify(payload),
    });

    if (!res.ok) {
      const error = await res.text();
      throw new Error(`Confluence create failed (${res.status}): ${error}`);
    }
  }

  private async updatePage(id: string, newVersion: number, title: string, body: string): Promise<void> {
    const res = await fetchWithTimeout(`https://${this.domain}/wiki/rest/api/content/${encodeURIComponent(id)}`, {
      method: 'PUT',
      headers: this.headers(),
      body: JSON.stringify({
        type: 'page',
        title,
        version: { number: newVersion },
        body: {
          storage: { value: body, representation: 'storage' },
        },
      }),
    });

    if (!res.ok) {
      const error = await res.text();
      throw new Error(`Confluence update failed (${res.status}): ${error}`);
    }
  }

  private headers(): Record<string, string> {
    const auth = Buffer.from(`${this.email}:${this.apiToken}`).toString('base64');
    return {
      'Authorization': `Basic ${auth}`,
      'Content-Type': 'application/json',
      'Accept': 'application/json',
    };
  }
}
