import type { Publisher, ReleaseNotes, OutputFormat } from '@cullit/core';
import { fetchWithTimeout, createLogger } from '@cullit/core';

const log = createLogger();

/**
 * Posts release notes to Discord via webhook.
 */
export class DiscordPublisher implements Publisher {
  constructor(private webhookUrl: string) {
    if (!webhookUrl.startsWith('https://discord.com/api/webhooks/') && !webhookUrl.startsWith('https://discordapp.com/api/webhooks/')) {
      throw new Error('Invalid Discord webhook URL — must start with https://discord.com/api/webhooks/');
    }
  }

  async publish(notes: ReleaseNotes, _format: OutputFormat): Promise<void> {
    const content = this.buildDiscordMessage(notes);

    const response = await fetchWithTimeout(this.webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        embeds: [{
          title: `Release ${notes.version}`,
          description: content,
          color: 0xe8ff47,
          timestamp: new Date().toISOString(),
          footer: { text: 'Generated by Cullit' },
        }],
      }),
    });

    if (!response.ok) {
      throw new Error(`Discord webhook failed (${response.status})`);
    }
    log.info('✓ Published to Discord');
  }

  private buildDiscordMessage(notes: ReleaseNotes): string {
    let msg = '';
    if (notes.summary) msg += `${notes.summary}\n\n`;

    for (const change of notes.changes) {
      msg += `• ${change.description}`;
      if (change.ticketKey) msg += ` (${change.ticketKey})`;
      msg += '\n';
    }

    return msg.substring(0, 4000);
  }
}
