import type { Publisher, ReleaseNotes, OutputFormat } from '@cullit/core';
import { fetchWithTimeout, createLogger } from '@cullit/core';

const log = createLogger();

/**
 * Publishes release notes to a Notion database.
 * Each release = a database row with properties + content blocks.
 * 
 * Requires NOTION_API_KEY and a publish target with:
 *   - databaseId: the Notion database ID to add pages to
 */
export class NotionPublisher implements Publisher {
  private apiKey: string;
  private databaseId: string;

  constructor(config: { databaseId: string }) {
    if (!config.databaseId) {
      throw new Error('Notion databaseId is required in publish config');
    }
    // Notion database IDs are 32-char hex (with or without dashes)
    const cleanId = config.databaseId.replace(/-/g, '');
    if (!/^[a-f0-9]{32}$/i.test(cleanId)) {
      throw new Error('Invalid Notion databaseId format');
    }
    this.databaseId = config.databaseId;

    this.apiKey = process.env.NOTION_API_KEY || '';
    if (!this.apiKey) {
      throw new Error('NOTION_API_KEY not configured. Create an integration at https://www.notion.so/my-integrations');
    }
  }

  async publish(notes: ReleaseNotes, _format: OutputFormat): Promise<void> {
    const properties = this.buildProperties(notes);
    const children = this.buildBlocks(notes);

    const res = await fetchWithTimeout('https://api.notion.com/v1/pages', {
      method: 'POST',
      headers: this.headers(),
      body: JSON.stringify({
        parent: { database_id: this.databaseId },
        properties,
        children,
      }),
    });

    if (!res.ok) {
      const error = await res.text();
      throw new Error(`Notion API failed (${res.status}): ${error}`);
    }

    log.info(`✓ Published to Notion database`);
  }

  private buildProperties(notes: ReleaseNotes): Record<string, unknown> {
    return {
      // "Name" / "Title" property — most Notion databases have this
      Name: {
        title: [{ text: { content: `Release ${notes.version}` } }],
      },
      Version: {
        rich_text: [{ text: { content: notes.version } }],
      },
      Date: {
        date: { start: notes.date },
      },
      Changes: {
        number: notes.changes.length,
      },
    };
  }

  private buildBlocks(notes: ReleaseNotes): Array<Record<string, unknown>> {
    const blocks: Array<Record<string, unknown>> = [];

    // Summary
    if (notes.summary) {
      blocks.push({
        type: 'paragraph',
        paragraph: {
          rich_text: [{ type: 'text', text: { content: notes.summary } }],
        },
      });
    }

    // Group changes by category
    const categoryLabels: Record<string, string> = {
      features: '✨ Features', fixes: '🐛 Bug Fixes', breaking: '⚠️ Breaking Changes',
      improvements: '🔧 Improvements', chores: '🧹 Chores', other: '📝 Other',
    };
    const order = ['breaking', 'features', 'improvements', 'fixes', 'chores', 'other'];

    const grouped = new Map<string, typeof notes.changes>();
    for (const change of notes.changes) {
      const list = grouped.get(change.category) || [];
      list.push(change);
      grouped.set(change.category, list);
    }

    for (const cat of order) {
      const entries = grouped.get(cat);
      if (!entries?.length) continue;

      blocks.push({
        type: 'heading_3',
        heading_3: {
          rich_text: [{ type: 'text', text: { content: categoryLabels[cat] || cat } }],
        },
      });

      for (const entry of entries) {
        let content = entry.description;
        if (entry.ticketKey) content += ` (${entry.ticketKey})`;

        blocks.push({
          type: 'bulleted_list_item',
          bulleted_list_item: {
            rich_text: [{ type: 'text', text: { content } }],
          },
        });
      }
    }

    // Footer
    if (notes.metadata) {
      blocks.push({
        type: 'paragraph',
        paragraph: {
          rich_text: [{
            type: 'text',
            text: { content: `Generated by Cullit • ${notes.metadata.commitCount} commits, ${notes.metadata.prCount} PRs` },
            annotations: { italic: true, color: 'gray' },
          }],
        },
      });
    }

    return blocks;
  }

  private headers(): Record<string, string> {
    return {
      'Authorization': `Bearer ${this.apiKey}`,
      'Content-Type': 'application/json',
      'Notion-Version': '2022-06-28',
    };
  }
}
