import type { Publisher, ReleaseNotes, OutputFormat } from '@cullit/core';
import { fetchWithTimeout, createLogger } from '@cullit/core';

const log = createLogger();

/**
 * Posts release notes to Microsoft Teams via Incoming Webhook.
 * Uses Adaptive Card format for rich rendering.
 */
export class TeamsPublisher implements Publisher {
  constructor(private webhookUrl: string) {
    // Validate domain to prevent SSRF — must be an Office 365 webhook host
    const parsed = new URL(webhookUrl);
    if (parsed.protocol !== 'https:' || !parsed.hostname.endsWith('.webhook.office.com')) {
      throw new Error('Invalid Teams webhook URL — must be an Office 365 webhook URL');
    }
  }

  async publish(notes: ReleaseNotes, _format: OutputFormat): Promise<void> {
    const card = this.buildAdaptiveCard(notes);

    const response = await fetchWithTimeout(this.webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(card),
    });

    if (!response.ok) {
      throw new Error(`Teams webhook failed (${response.status})`);
    }
    log.info('✓ Published to Microsoft Teams');
  }

  private buildAdaptiveCard(notes: ReleaseNotes): object {
    const categoryEmoji: Record<string, string> = {
      features: '✨', fixes: '🐛', breaking: '⚠️',
      improvements: '🔧', chores: '🧹', other: '📝',
    };

    const changeItems = notes.changes.map(change => {
      const emoji = categoryEmoji[change.category] || '•';
      let text = `${emoji} ${change.description}`;
      if (change.ticketKey) text += ` (${change.ticketKey})`;
      return { type: 'TextBlock', text, wrap: true, spacing: 'Small' };
    });

    return {
      type: 'message',
      attachments: [{
        contentType: 'application/vnd.microsoft.card.adaptive',
        content: {
          $schema: 'http://adaptivecards.io/schemas/adaptive-card.json',
          type: 'AdaptiveCard',
          version: '1.4',
          body: [
            {
              type: 'TextBlock',
              text: `Release ${notes.version}`,
              weight: 'Bolder',
              size: 'Large',
            },
            {
              type: 'TextBlock',
              text: notes.date,
              isSubtle: true,
              spacing: 'None',
            },
            ...(notes.summary ? [{
              type: 'TextBlock',
              text: notes.summary,
              wrap: true,
              spacing: 'Medium',
            }] : []),
            { type: 'TextBlock', text: '---', spacing: 'Medium' },
            ...changeItems,
            ...(notes.metadata ? [{
              type: 'TextBlock',
              text: `Generated by Cullit • ${notes.metadata.commitCount} commits`,
              isSubtle: true,
              size: 'Small',
              spacing: 'Large',
            }] : []),
          ],
        },
      }],
    };
  }
}
